### PR TITLE
Manual firing now invokes callback

### PR DESCRIPTION
**Pull request by tomazzaman**
Did a bit of code-housekeeping and introduced *jshint*, so the build will fail unless the code is well written :) Also introduced an additional test for manual fire.

### CODE REVIEW

**Comment by carlsednaoui** [comment]
Thanks @tomazzaman I'll take a look this weekend.

**Comment by tomazzaman** [comment]
You're welcome!

**Comment by tomazzaman** [comment]
By the way, I've also written a tutorial on using [Oubounce with WordPress](https://codeable.io/community/how-to-build-your-own-wordpress-email-form-optin-form/):

**Comment by carlsednaoui** [comment]
Damn, nice PR. Thanks @tomazzaman.

Let me add your tutorial to the README too :smile:

**Comment by tomazzaman** [comment]
Thanks, glad I could help :)

**Pull request merged**
