### PR TITLE
Add `detectEdges` flag to determine when the user leaves the edge of the window

### PR DESCRIPTION
**Pull request by dempfi**

### CODE REVIEW

**Comment by jgoyon** [comment]
Hi, is there a plan to merge this PR ?
I [started to implement this feature](https://github.com/jgoyon/ouibounce/commit/9fbae927b1031779d874a0d8198e1794771c6563)  on my side but discovered the PR of @dempfi already implement it.

**Comment by dempfi** [comment]
hi @carlsednaoui can you please take a look at this PR?

**Comment by carlsednaoui** [comment]
Thanks for the note, Ike. As you can see, I've been a bit absent when it
comes to open source :(

Will try to jump back into the ouibounce train soon!

**Comment by dempfi** [comment]
I know how it happens :) no worries

**Pull request closed without merging**
